.\" $Id$
.TH ezmlm-mktab 1
.SH NAME
ezmlm-mktab \- create SQL table definition for ezmlm list
.SH SYNOPSIS
.B ezmlm-mktab
[
.B \-dC
]
.I table_root
.SH DESCRIPTION
.B ezmlm-mktab
takes
.I table_root
and prints table definitions for
.IR table_root ,
.IR table_root\fB_slog ,
etc. All subscriber
and log tables are defined, although normally only a subset are used.

.B ezmlm-mktab
also can also print the SQL drop commands to remove the same tables.
.SH OPTIONS
.TP
.B \-C
Do not print the table definitions for list creation. By default, table
definitions are printed.
.TP
.B \-d
Print table drop commands. Normally, they are omitted. When printed, they
are printed before the table definitions, so that existing tables are removed,
then recreated.
.SH USAGE
.B ezmlm-mktab
.B \-d
.I list \fR | mysql -hhost -uuser -p -f db

This connects to the mysql server on ``host'' as ``user'' (prompting for
the password) and in database ``db'' creates tables
.IR list ,
.IR list\fB_slog ,
.IR list\fB_mlog ,
the corresponding table sets for address lists
.IR list\fB_allow ,
.IR list\fB_deny ,
.IR list\fB_digest,
.IR list\fB_mod,
as well as
.IR list\fB_name ,
.IR list\fB_digest_name ,
.IR list\fB_cookie ,
and
.IR list\fB_digest_cookie .

Since the
.B \-d
switch is used, any of these tables already existing are first dropped,
with loss of any data already in them.
.SH "SEE ALSO"
ezmlm-send(1),
ezmlm(5),
mysql(1)
