.\" $Id$
.TH ezmlm-unsub 1
.SH NAME
ezmlm-unsub \- manually remove addresses from a mailing list
.SH SYNOPSIS
.B ezmlm-unsub
[
.B \-HmMnNvV
] [
.B \-h
.I hash
]
.I dir
[
.I subdir
]
[
.I box\fB@\fIdomain
[
.I name
]
.I ...
]
.SH DESCRIPTION
.B ezmlm-unsub
removes each address
.I box\fB@\fIdomain
from the mailing list stored in
.IR dir / subdir .
.I name
is added as a comment to the subscription log, if the
.B \-n
switch is used.

If no argument is given on the command line,
.B ezmlm-unsub
will process standard input instead.

If
.I box\fB@\fIdomain
is not on the mailing list,
.B ezmlm-unsub
keeps it off.

.B ezmlm-unsub
converts
.I domain
to lowercase before removing
.I box\fB@\fIdomain
from the mailing list.

.SH "GENERAL OPTIONS"
.TP
.B \-h \fIhash
With SQL support, the argument is used as the hash. The argument should
be between 1 and 99. The hash is used in
in the distribution of addresses between sublists. As the hash is normally
between 0 and 52, controlling the hash makes it possible to add addresses
that cannot be manipulated remotely.
.TP
.B \-H
(Default.)
The address can be removed if it has a hash in the normal range
(0..52).  Only used by SQL subscriber databases.
.TP
.B \-m
(Default.)
Use the configured subscriber database for the list.
.TP
.B \-M
Use the standard subscriber database even if the list was configured to
use another plugin.  This is equivalent to specifying
.B \-S
.IR std .
.TP
.B \-n
Assume arguments are pairs of
.I box\fB@\fIdomain
and
.IR name
(or other subscriber info)
rather than addresses alone.
.B ezmlm-unsub(1)
will remove the first argument in each pair from the subscriber list. If
it is a new address,
.I name
will be added to the subscription log.
.TP
.B \-N
(Default.)
Arguments are all addresses of the type
.IR box\fB@\fIdomain .
.TP
.B \-S\fI subdb
Connect to the given subscriber database plugin.  This option can be
used to manipulate alternate subscriber databases.  The contents of the
parameter should be the same as would be given to
.B ezmlm-make -6\fR.
Use in combination with
.B ezmlm-list(1)
to convert an SQL address db to a ezmlm standard address database.
.TP
.B \-v
Display
.B ezmlm-unsub(1)
version information.
.TP
.B \-V
Display
.B ezmlm-unsub(1)
version information.
.SH "SEE ALSO"
ezmlm-list(1),
ezmlm-manage(1),
ezmlm-make(1),
ezmlm-receipt(1),
ezmlm-send(1),
ezmlm-sub(1),
ezmlm(5)
