#!/bin/sh
#$Id$

t=Makefile.targets
trap 'rm -fv *.tmp.$$; rm -r $t' EXIT
rm -rf $t
mkdir -p $t
rm -f `cat TARGETS`

c() {
    echo "$*" >&2;
}

error() {
    echo "$0: Error: $*" >&2;
}

dependon() {
    for dep in $*; do
	echo "$dep" >&3
	target $dep
    done
}

formake() {
    echo "	$*" >&4
}

nosuchtarget() {
    error "No such target: $target";
}

directtarget() {
    # What is this supposed to do?
    :
}

dependcc() {
    dependon $1
    dependon `cpp -M -MM -MG $1 2>/dev/null \
              | sed -e 's/^[^ ]*://' -e 's/\\\\//'`
}

depend() {
    # What is this supposed to do?
    # Invoked as: depend -ezmlm-warn.o=m
    :
}

target() {
    target=$1
    if [ -e $target -o -e $t/$target.deps ]; then
	return
    fi
    #c target: $target
    tmp=$target.tmp.$$
    (
	ext=${target##*.}
	base=${target%%.*}
	if [ -f $target.do ]; then
	    . $target.do
	elif [ -f default.$ext.do ]; then
	    . default.$ext.do $target $base $tmp
	else
	    . default.do $target $base $tmp
	fi
    ) 3>$t/$target.deps 4>$t/$target.cmds
#    if [ -s $tmp ]; then
#	mv -f $tmp $target
#    else
#	rm -f $tmp
#    fi
}

echo "Calculating targets..."
target clean
target targets
rm -f $t/targets

echo "Building Makefile..."
(
    cat <<EOF
# This file is automatically generated, do not edit.
SHELL=/bin/sh
default: it
EOF
    cd $t
    for deps in *.deps; do
	target=${deps%.deps}
	cmds=$target.cmds
	if [ -s $deps -o -s $cmds ]; then
	    echo
	    echo "$target: \\"
	    echo `uniq $deps`
	    cat $cmds
	fi
	rm -f $deps $cmds
    done
) >Makefile

echo "done."
