#ifndef MSGTXT_H
#define MSGTXT_H

extern void msgtxt_init(void);
extern const char *MSG(const char* name);
extern const char *MSG1(const char *name,const char *p1);
extern const char *MSG2(const char *name,const char *p1,const char *p2);

#define ERR_NOMEM MSG("ERR_NOMEM")
#define ERR_NOCMD MSG("ERR_NOCMD")
#define ERR_CLOSE MSG("ERR_CLOSE")
#define ERR_WRITE MSG("ERR_WRITE")
#define ERR_READ MSG("ERR_READ")
#define ERR_READ_KEY MSG("ERR_READ_KEY")
#define ERR_FLUSH MSG("ERR_FLUSH")
#define ERR_SEEK MSG("ERR_SEEK")
#define ERR_SYNC MSG("ERR_SYNC")
#define ERR_CHMOD MSG("ERR_CHMOD")
#define ERR_STAT MSG("ERR_STAT")
#define ERR_DELETE MSG("ERR_DELETE")
#define ERR_READ_INPUT MSG("ERR_READ_INPUT")
#define ERR_SEEK_INPUT MSG("ERR_SEEK_INPUT")
#define ERR_CREATE MSG("ERR_CREATE")
#define ERR_MOVE MSG("ERR_MOVE")
#define ERR_OPEN MSG("ERR_OPEN")
#define ERR_OBTAIN MSG("ERR_OBTAIN")
#define ERR_OPEN_LOCK MSG("ERR_OPEN_LOCK")
#define ERR_OBTAIN_LOCK MSG("ERR_OBTAIN_LOCK")
#define ERR_NOLOCAL MSG("ERR_NOLOCAL")
#define ERR_NODEFAULT MSG("ERR_NODEFAULT")
#define ERR_NODTLINE MSG("ERR_NODTLINE")
#define ERR_NOSENDER MSG("ERR_NOSENDER")
#define ERR_NOHOST MSG("ERR_NOHOST")
#define ERR_NOEXIST MSG("ERR_NOEXIST")
#define ERR_NOEXIST_KEY MSG("ERR_NOEXIST_KEY")
#define ERR_SWITCH MSG("ERR_SWITCH")
#define ERR_BOUNCE MSG("ERR_BOUNCE")
#define ERR_ANONYMOUS MSG("ERR_ANONYMOUS")
#define ERR_NOT_PUBLIC MSG("ERR_NOT_PUBLIC")
#define ERR_NOT_ARCHIVED MSG("ERR_NOT_ARCHIVED")
#define ERR_NOT_INDEXED MSG("ERR_NOT_INDEXED")
#define ERR_NOT_AVAILABLE MSG("ERR_NOT_AVAILABLE")
#define ERR_NOT_ALLOWED MSG("ERR_NOT_ALLOWED")
#define ERR_BAD_ADDRESS MSG("ERR_BAD_ADDRESS")
#define ERR_BAD_RETURN_ADDRESS MSG("ERR_BAD_RETURN_ADDRESS")
#define ERR_BAD_REQUEST MSG("ERR_BAD_REQUEST")
#define ERR_QMAIL_QUEUE MSG("ERR_QMAIL_QUEUE")
#define ERR_TMP_QMAIL_QUEUE MSG("ERR_TMP_QMAIL_QUEUE")
#define ERR_NOT_PARENT MSG("ERR_NOT_PARENT")
#define ERR_SUBLIST MSG("ERR_SUBLIST")
#define ERR_MAILING_LIST MSG("ERR_MAILING_LIST")
#define ERR_LOOPING MSG("ERR_LOOPING")
#define ERR_SUBSCRIBER_CAN MSG("ERR_SUBSCRIBER_CAN")
#define ERR_571 MSG("ERR_571")
#define ERR_EMPTY_DIGEST MSG("ERR_EMPTY_DIGEST")
#define ERR_EMPTY_LIST MSG("ERR_EMPTY_LIST")
#define ERR_NOINDEX MSG("ERR_NOINDEX")
#define ERR_BAD_INDEX MSG("ERR_BAD_INDEX")
#define ERR_BAD_DIGCODE MSG("ERR_BAD_DIGCODE")
#define ERR_UNEXPECTED MSG("ERR_UNEXPECTED")
#define ERR_BAD_ALL MSG("ERR_BAD_ALL")
#define ERR_MIME_QUOTE MSG("ERR_MIME_QUOTE")
#define ERR_SUBST_UNSAFE MSG("ERR_SUBST_UNSAFE")

/* ezmlm-request unique */
#define ERR_REQ_LISTNAME MSG("ERR_REQ_LISTNAME")
#define ERR_REQ_LOCAL MSG("ERR_REQ_LOCAL")

/* ezmlm-reject unique */
#define ERR_MAX_SIZE MSG("ERR_MAX_SIZE")
#define ERR_MIN_SIZE MSG("ERR_MIN_SIZE")
#define ERR_SIZE_CODE MSG("ERR_SIZE_CODE")
#define ERR_NO_ADDRESS MSG("ERR_NO_ADDRESS")
#define ERR_NO_SUBJECT MSG("ERR_NO_SUBJECT")
#define ERR_SUBCOMMAND MSG("ERR_SUBCOMMAND")
#define ERR_BODYCOMMAND MSG("ERR_BODYCOMMAND")
#define ERR_BAD_TYPE MSG("ERR_BAD_TYPE")
#define ERR_BAD_PART MSG("ERR_BAD_PART")
#define ERR_JUNK MSG("ERR_JUNK")

/* ezmlm-manage unique */
#define ERR_SUB_NOP MSG("ERR_SUB_NOP")
#define ERR_UNSUB_NOP MSG("ERR_UNSUB_NOP")
#define ERR_BAD_NAME MSG("ERR_BAD_NAME")
#define ERR_NO_MARK MSG("ERR_NO_MARK")
#define ERR_EDSIZE MSG("ERR_EDSIZE")
#define ERR_BAD_CHAR MSG("ERR_BAD_CHAR")
#define ERR_EXTRA_SUB MSG("ERR_EXTRA_SUB")
#define ERR_EXTRA_UNSUB MSG("ERR_EXTRA_UNSUB")


/* ezmlm-moderation functions unique */
#define ERR_MOD_TIMEOUT MSG("ERR_MOD_TIMEOUT")
#define ERR_MOD_ACCEPTED MSG("ERR_MOD_ACCEPTED")
#define ERR_MOD_REJECTED MSG("ERR_MOD_REJECTED")
#define ERR_MOD_COOKIE MSG("ERR_MOD_COOKIE")
#define ERR_FORK MSG("ERR_FORK")
#define ERR_EXECUTE MSG("ERR_EXECUTE")
#define ERR_CHILD_CRASHED MSG("ERR_CHILD_CRASHED")
#define ERR_CHILD_FATAL MSG("ERR_CHILD_FATAL")
#define ERR_CHILD_TEMP MSG("ERR_CHILD_TEMP")
#define ERR_CHILD_UNKNOWN MSG("ERR_CHILD_UNKNOWN")
#define ERR_UNIQUE MSG("ERR_UNIQUE")
#define ERR_NO_POST MSG("ERR_NO_POST")

/* ezmlm-make unique */
#define ERR_VERSION MSG("ERR_VERSION")
#define ERR_ENDTAG MSG("ERR_ENDTAG")
#define ERR_LINKDIR MSG("ERR_LINKDIR")
#define ERR_FILENAME MSG("ERR_FILENAME")
#define ERR_PERIOD MSG("ERR_PERIOD")
#define ERR_SLASH MSG("ERR_SLASH")
#define ERR_NEWLINE MSG("ERR_NEWLINE")
#define ERR_QUOTE MSG("ERR_QUOTE")
#define ERR_SYNTAX MSG("ERR_SYNTAX")
#define ERR_MKTAB MSG("ERR_MKTAB")

/* ezmlm-limit unique */
#define ERR_EXCESS_MOD MSG("ERR_EXCESS_MOD")
#define ERR_EXCESS_DEFER MSG("ERR_EXCESS_DEFER")

/* ezmlm-cron unique */
#define ERR_SAME_HOST MSG("ERR_SAME_HOST")
#define ERR_DOW MSG("ERR_DOW")
#define ERR_NOT_CLEAN MSG("ERR_NOT_CLEAN")
#define ERR_SUID MSG("ERR_SUID")
#define ERR_UID MSG("ERR_UID")
#define ERR_EUID MSG("ERR_EUID")
#define ERR_BADUSER MSG("ERR_BADUSER")
#define ERR_BADHOST MSG("ERR_BADHOST")
#define ERR_BADLOCAL MSG("ERR_BADLOCAL")
#define ERR_LISTNO MSG("ERR_LISTNO")
#define ERR_NO_MATCH MSG("ERR_NO_MATCH")
#define ERR_SETUID MSG("ERR_SETUID")
#define ERR_CFHOST MSG("ERR_CFHOST")
#define ERR_EXCLUSIVE MSG("ERR_EXCLUSIVE")
#define ERR_CRONTAB MSG("ERR_CRONTAB")

/* ezmlm-gate */
#define ERR_REJECT MSG("ERR_REJECT")

/* issub/subscribe ... */
#define ERR_ADDR_AT MSG("ERR_ADDR_AT")
#define ERR_ADDR_LONG MSG("ERR_ADDR_LONG")
#define ERR_ADDR_NL MSG("ERR_ADDR_NL")

/* sql */
#define ERR_COOKIE MSG("ERR_COOKIE")
#define ERR_NOT_ACTIVE MSG("ERR_NOT_ACTIVE")
#define ERR_PARSE MSG("ERR_PARSE")
#define ERR_DONE MSG("ERR_DONE")
#define ERR_MAX_BOUNCE MSG("ERR_MAX_BOUNCE")
#define ERR_NO_PLUGIN MSG("ERR_NO_PLUGIN")
#define ERR_NO_ABSOLUTE MSG("ERR_NO_ABSOLUTE")
#define ERR_NO_LEVELS MSG("ERR_NO_LEVELS")

#endif
