#!/usr/bin/python2
import glob
import os
import re
import sys

try:
	lang = sys.argv[1]
except:
	print 'Usage: %s LANG' % sys.argv[0]

re_msg = re.compile('MSG\d?\(([A-Z][A-Z_]*)')
src_msgs = { }
for src in glob.glob('*.c'):
	for msg in re_msg.findall(file(src).read()):
		src_msgs[msg] = src

SPLIT = ':'
lang_msgs = dict([
	line[:-1].split(SPLIT, 1)
	for line in file('lang/%s/text/messages' % lang).readlines()
	if line[0] <> '#' and line[0] <> '\n' and SPLIT in line
	])

missing = 0
extra = 0

for msg,src in src_msgs.items():
	if not lang_msgs.has_key(msg):
		print 'Missing:', msg, 'in file', src
		missing += 1

for msg in lang_msgs.keys():
	if not src_msgs.has_key(msg):
		print 'Extra:', msg
		extra += 1

if missing > 0 or extra > 0:
	print 'Summary: %d missing, %d extra messages' % (missing, extra)
