#!/usr/bin/python2
import os
import re
import sys

try:
	lang = sys.argv[1]
except:
	print 'Usage: %s LANG' % sys.argv[0]

re_msg = re.compile('^#define\s+\S+\s+"([^"]+)"$', re.MULTILINE)
src_msgs = re_msg.findall(file('messages.h').read())

SPLIT = '|'
lang_msgs = dict([
	line[:-1].split(SPLIT, 1)
	for line in file('lang/%s/text/messages' % lang).readlines()
	if line[0] <> '#' and line[0] <> '\n' and SPLIT in line
	])

missing = 0
extra = 0

for msg in src_msgs:
	if not lang_msgs.has_key(msg):
		print 'Missing:', msg
		missing += 1

src_msgs = dict(zip(src_msgs, [None]*len(src_msgs)))
for msg in lang_msgs.keys():
	if not src_msgs.has_key(msg):
		print 'Extra:', msg
		extra += 1

if missing > 0 or extra > 0:
	print 'Summary: %d missing, %d extra messages' % (missing, extra)
