#!/bin/bash
set -e

getrev() {
  local rev
  rev=`sed -e '/^#* *Revision: /!d; s/^.*: //' $1`
  echo ${rev:-0}
}

cd `dirname $0`/../lang
noupdates=true
for en in en_US/text/*; do
  if [ $en = en_US/text/messages ]; then
    continue
  fi
  base=${en#en_US/text/}
  baserev=`getrev $en`
  missing=""
  old=""
  for lang in ?? ??_??; do
    if [ $lang != en_US ]; then
      other=$lang/text/$base
      if ! [ -e $other ]; then
	missing="$missing $lang"
      else
        otherrev=`getrev $other`
        if [ "$baserev" -gt "$otherrev" ]; then
	  old="$old $lang"
        fi
      fi
    fi
  done
  if [ -n "$missing" ]; then
    echo "Translation for $base is missing for the following languages:"
    echo "  $missing"
    noupdates=false
  fi
  if [ -n "$old" ]; then
    echo "Translation for $base is out of date for the following languages:"
    echo "  $old"
    noupdates=false
  fi
done

if $noupdates; then
  echo "No language files appear out of date."
fi
