#!/bin/sh
# $Id$

doit() {
  lang=$1
  echo "d:::755:/$lang::"
  ls -1 lang/$lang | while read file; do
    if [ $file = sed ]; then
      continue
    fi
    path=lang/$lang/$file
    if [ -d $path ]; then
      doit $lang/$file
    else
      echo "c:::644:/$lang/:$file:lang/$lang/$file"
    fi
  done
}

{
  echo "d:::755:::"
  echo "c:::644:/:ezmlmglrc:"
  echo "c:::644:/:ezmlmsubrc:"

  ls -1 lang | while read lang; do
    doit $lang
  done

} >ETC
