#!/bin/bash
set -e

if ! [ -s CHANGES -a -s README -a -s VERSION ]; then
  echo "Run this script from in the ezmlm-idx source directory."
  exit 1
fi

base=`sed -e q VERSION`

if ! grep -q "^${base}, " CHANGES; then
  echo "$0: CHANGES is missing release stamp."
  exit 1
fi

if ! grep -q " ${base}, " HISTORY; then
  echo "$0: HISTORY is missing release stamp."
  exit 1
fi

git checkout conf-*

tools/makemake

# Need to regenerate the spec before copying
make ezmlm-idx.spec

echo "Setting up the temporary directory"
mkdir $base
trap 'rm -r $base' EXIT

# Copy the base set of files
cp --parents `cat SOURCES EXTRADIST` $base/
find lang -type f -print \
| xargs cp --parents --target-directory=$base/

# Strip out the warnings options from conf-cc
sed -e 's/ -W[^ ]*//g' conf-cc >$base/conf-cc

# Make sure all files are at least readable, just in case
chmod -R +r $base

echo "Generating ChangeLog"
git log >$base/ChangeLog

echo "Generating FILES"
( cd $base && find * -type f >FILES )

echo "Creating final tarball"
tar -czf $base.tar.gz $base
ls -l $base.tar.gz
