#!/bin/bash
set -e

if ! [ -s CHANGES.idx -a -s README.idx -a -s VERSION ]; then
  echo "Run this script from in the ezmlm-idx source directory."
  exit 1
fi

version=`sed -e 's/^ezmlm-idx-//' -e q VERSION`
base=ezmlm-idx-$version

if ! grep -q "^${base}, " CHANGES.idx; then
  echo "$0: CHANGES.idx is missing release stamp."
  exit 1
fi

if ! grep -q " ${base}, " HISTORY; then
  echo "$0: HISTORY is missing release stamp."
  exit 1
fi

svn revert conf-*

tools/makemake

echo "Building the idx.patch"
tools/makepatch

echo "Setting up the temporary directory"
trap 'rm -r $base' EXIT
mkdir $base
cp --parents `cat SOURCES EXTRADIST` $base/
find sub_* lang -name .svn -prune -o -type f -print \
| xargs cp --parents --target-directory=$base/
mv idx.patch $base/
sed -e 's/ -W[^ ]*//g' conf-cc >$base/conf-cc
chmod -R +r $base

#echo "Building symlinks"
#make -C $base symlinks

echo "Removing ezmlm-0.53 sources"
fgrep -vxf REPLACED FILES \
| ( cd $base && xargs rm -f; )

echo "Generating ChangeLog"
svn log --verbose file:///home/subversion/repos/ezmlm-idx >$base/ChangeLog

echo "Generating FILES.idx"
( cd $base && find * -type f >FILES.idx )

echo "Creating final tarball"
tar -czf $base.tar.gz $base
chmod 444 $base.tar.gz
ls -l $base.tar.gz
