#!/bin/sh
make "$@" 2>&1 >/dev/null | \
sed	-e "
  /: warning: passing arg 2 of \`sgetoptmine' from incompatible /d;
  /: warning: return type of [\`']main' is not [\`']int'$/d;
  /^ezmlm-.*\\.c: In function \`main':$/d;
"
