#!/bin/sh
make "$@" 2>&1 >/dev/null | \
sed	-e "/: warning: passing arg 2 of \`sgetoptmine' from incompatible /d" \
	-e "/: warning: return type of \`main' is not \`int'$/d" \
	-e "/^ezmlm-.*\\.c: In function \`main':$/d"
