#!/bin/sh
# $Id$

langs=`cd text && echo ?? ??_??`
{
  echo "d:::755:::"
  echo "c:::644:/:ezmlmglrc:"
  echo "c:::644:/:ezmlmrc:"
  echo "c:::644:/:ezmlmsubrc:"

  for lang in $langs
  do
    echo "c:::644:/:ezmlmrc.$lang"
  done

  for lang in $langs
  do
    echo "d:::755:/$lang::"
    ls -1 text/$lang | while read text
    do
      echo "c:::644:/$lang/:$text:lang/$lang/$text"
    done
  done

} >ETC
