#!/bin/sh
set -e

sub_mysql/ezmlm-mktab -d -C list | mysql --force eztest >/dev/null 2>&1
sub_mysql/ezmlm-mktab list | mysql eztest

./ezmlm-test -d eztest -p '' -h mysql

sub_mysql/ezmlm-mktab -d -C list | mysql eztest
