#!/bin/sh
set -e

./ezmlm-mktab-mysql -d -C list | mysql --force eztest >/dev/null 2>&1
./ezmlm-mktab-mysql list | mysql eztest

./ezmlm-test -d eztest -p '' -h mysql

./ezmlm-mktab-mysql -d -C list | mysql eztest
