#!/bin/sh
set -e

./ezmlm-mktab -d -C list | psql -h pgsql eztest >/dev/null 2>&1
./ezmlm-mktab list | psql -h pgsql eztest

./ezmlm-test -d eztest -p '' -h pgsql

./ezmlm-mktab -d -C list | psql -h pgsql eztest
