#!/bin/sh
set -e

if [ $# -ne 1 ]; then
  echo "usage: $0 [std|mysql|pgsql]"
  exit 1
fi
db=$1

echo "==================== Testing subdb = $db ===================="

`dirname $0`/makerrors
if [ $db != 'std' ]; then
  `dirname $0`/makerrors $db
fi

exec ${0}-$db
