#!/bin/sh
set -e

if [ $# -ne 1 ]; then
  echo "usage: $0 [std|mysql|pgsql]"
  exit 1
fi
db=$1

if [ `head -n 1 conf-bin` != `pwd` ]; then
  pwd >conf-bin
fi

if [ `head -n 1 conf-etc` != `pwd`/lang ]; then
  echo `pwd`/lang >conf-etc
fi

if [ `head -n 1 conf-lib` != `pwd` ]; then
  pwd >conf-lib
fi

echo "==================== Testing conf-sub = $db ===================="

`dirname $0`/makerrors
if [ $db != 'std' ]; then
  `dirname $0`/makerrors sub-${db}.so
  rm sub-sql.so
  ln -s sub-${db}.so sub-sql.so
fi

exec ${0}-$db
